In [1]:
import numpy as np
import pandas as pd

In [15]:
air_quality = pd.read_csv('Air_Quality.csv')
air_quality

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
0,179772,640,Boiler Emissions- Total SO2 Emissions,Number per km2,number,UHF42,409.0,Southeast Queens,2015,01/01/2015,0.3,NaN
1,179785,640,Boiler Emissions- Total SO2 Emissions,Number per km2,number,UHF42,209.0,Bensonhurst - Bay Ridge,2015,01/01/2015,1.2,NaN
2,178540,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,209.0,Bensonhurst - Bay Ridge,Annual Average 2012,12/01/2011,8.6,NaN
3,178561,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,409.0,Southeast Queens,Annual Average 2012,12/01/2011,8.0,NaN
4,823217,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,409.0,Southeast Queens,Summer 2022,06/01/2022,6.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
18020,816914,643,Annual vehicle miles traveled,Million miles,per square mile,CD,503.0,Tottenville and Great Kills (CD3),2019,01/01/2019,12.9,NaN
18021,816913,643,Annual vehicle miles traveled,Million miles,per square mile,CD,503.0,Tottenville and Great Kills (CD3),2010,01/01/2010,14.7,NaN
18022,816872,643,Annual vehicle miles traveled,Million miles,per square mile,UHF42,208.0,Canarsie - Flatlands,2010,01/01/2010,43.4,NaN
18023,816832,643,Annual vehicle miles traveled,Million miles,per square mile,UHF42,407.0,Southwest Queens,2010,01/01/2010,65.8,NaN
18024,151658,643,Annual vehicle miles traveled,Million miles,per square mile,UHF42,408.0,Jamaica,2005,01/01/2005,41.0,NaN

In [16]:
air_quality.sort_values(['Data Value'],ascending = False)

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
16166,130806,648,Asthma emergency department visits due to PM2.5,Estimated annual rate (under age 18),"per 100,000 children",UHF42,302.0,Central Harlem - Morningside Heights,2005-2007,01/01/2005,424.7,NaN
2864,130807,648,Asthma emergency department visits due to PM2.5,Estimated annual rate (under age 18),"per 100,000 children",UHF42,303.0,East Harlem,2005-2007,01/01/2005,354.2,NaN
6371,130792,648,Asthma emergency department visits due to PM2.5,Estimated annual rate (under age 18),"per 100,000 children",UHF42,106.0,High Bridge - Morrisania,2005-2007,01/01/2005,308.0,NaN
885,131431,648,Asthma emergency department visits due to PM2.5,Estimated annual rate (under age 18),"per 100,000 children",UHF42,303.0,East Harlem,2009-2011,01/01/2009,299.4,NaN
9603,131046,653,Asthma emergency departments visits due to Ozone,Estimated annual rate (under age 18),"per 100,000 children",UHF42,302.0,Central Harlem - Morningside Heights,2005-2007,01/01/2005,292.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9254,179817,641,Boiler Emissions- Total PM2.5 Emissions,Number per km2,number,UHF42,502.0,Stapleton - St. George,2015,01/01/2015,0.0,NaN
13604,130481,641,Boiler Emissions- Total PM2.5 Emissions,Number per km2,number,UHF42,409.0,Southeast Queens,2013,01/01/2013,0.0,NaN
15810,179770,640,Boiler Emissions- Total SO2 Emissions,Number per km2,number,UHF42,410.0,Rockaways,2015,01/01/2015,0.0,NaN
13676,130435,640,Boiler Emissions- Total SO2 Emissions,Number per km2,number,UHF42,501.0,Port Richmond,2013,01/01/2013,0.0,NaN
15030,828092,661,Asthma hospitalizations due to Ozone,Estimated annual rate (age 18+),"per 100,000 adults",UHF42,404.0,Bayside - Little Neck,2017-2019,01/01/2017,0.0,NaN

In [23]:
PM2022 = air_quality.loc[(air_quality["Time Period"] == 'Annual Average 2022') & (air_quality['Name'] == 'Fine particles (PM 2.5)')]
PM2022.sort_values(['Data Value'],ascending =False)

,Unique ID,Indicator ID,Name,Measure,Measure Info,Geo Type Name,Geo Join ID,Geo Place Name,Time Period,Start_Date,Data Value,Message
1554,823210,365,Fine particles (PM 2.5),Mean,mcg/m3,CD,105.0,Midtown (CD5),Annual Average 2022,01/01/2022,9.1,NaN
15798,823345,365,Fine particles (PM 2.5),Mean,mcg/m3,CD,102.0,Greenwich Village and Soho (CD2),Annual Average 2022,01/01/2022,8.4,NaN
14881,823255,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,306.0,Chelsea - Clinton,Annual Average 2022,01/01/2022,8.4,NaN
16788,823369,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF34,306308.0,Chelsea-Village,Annual Average 2022,01/01/2022,8.3,NaN
4832,823249,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,308.0,Greenwich Village - SoHo,Annual Average 2022,01/01/2022,8.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2072,823568,365,Fine particles (PM 2.5),Mean,mcg/m3,CD,414.0,Rockaway and Broad Channel (CD14),Annual Average 2022,01/01/2022,5.0,NaN
17731,823577,365,Fine particles (PM 2.5),Mean,mcg/m3,CD,503.0,Tottenville and Great Kills (CD3),Annual Average 2022,01/01/2022,5.0,NaN
16132,823468,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,410.0,Rockaways,Annual Average 2022,01/01/2022,5.0,NaN
2483,823375,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF34,410.0,Rockaways,Annual Average 2022,01/01/2022,5.0,NaN
16191,823456,365,Fine particles (PM 2.5),Mean,mcg/m3,UHF42,504.0,South Beach - Tottenville,Annual Average 2022,01/01/2022,5.0,NaN